### ISSUE TITLE
List of enrage IDs

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/LibDispellable-1.0#3]
wowhead finds 2 more enrage spells - 154982 and 180643, but the second one appears to be some battle pet related stuff.

In case it is of any use, I used the following two-liner to fetch the ids:
```powershell
$r = Invoke-RestMethod -Uri "http://www.wowhead.com/spells?filter=dt=9"
[regex]::matches($r, "_\[(\d+)\]={") | select value | %{ if ($_ -match "(\d+)"){[int]$matches[1]}} | sort -unique | out-file .\wowhead.txt
```

Could surely by written better, but I didn't know a thing about PowerShell two days ago :)

**Comment by Adirelle** [comment]
I didn't know how to fetch the data from wowhead, that's why I used wowdb in the first place. I'll take a look.
