### ISSUE TITLE
Legion Support

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/LibDispellable-1.0#5]
Legion introduced some changes to the dispel system:
- enrage effects are not dispelable anymore
- dispels are not modified by glyphs or talents anymore

It has to be checked if the Blizzard API still returns false positives and thus if this library is still needed.

**Comment by vendethiel** [comment]
Hey,

did you actually ended up taking a look at this? sorry for the 1year-and-1day bump

**Comment by vendethiel** [comment]
I guess your forks are good 👍

**Comment by Rainrider** [comment]
LibDispellable is on the throw-away list. You are better of pulling the DISPEL category form LibPlayerSpells. Either use you own handler or LibDispellable's `IterateDispellableAuras`. The later is how it is used in AdiButtonAuras [here](https://github.com/AdiAddons/AdiButtonAuras/blob/master/rules/Common.lua#L195-L225) but I'm looking to bake this into ABA itself and then dump LD for good.
